### ISSUE TITLE
Please, update to the last plantuml version (8047)

### ISSUE THREAD

**Issue by bondden** [markushedvall/plantuml-viewer#22]
Please, update to the actual plantuml version (8047). It has new features especially at deployment diagrams: http://plantuml.com/deployment.html
Thanks for the useful plugin!

**Comment by markushedvall** [comment]
The new 0.7.1 release uses 0.5.0 of node-plantuml containing plantuml version 8047.

It is now also possible to use your own plantuml jar file with the PLANTUML_HOME environment variable.
