### ISSUE TITLE
Save PNG automatically

### ISSUE THREAD

**Issue by alexec** [markushedvall/plantuml-viewer#26]
Hi,

I've switch to using your plugin as I love the real-time updating it does.

One feature of the other plugin I like is that saves a PNG of the diagram automatically with the same name.

E.g. if the PUML is named `mark.puml` it would create `mark.png` in the same directory.

 This would be a great feature to have on this plugin.

Alex

**Comment by markushedvall** [comment]
Hi,

I'm happy to hear that you are enjoying this plugin.

As for your request, it is definitely doable and shouldn't be too much work to add. I'll try to get some free time for implementing it soon.

**Comment by alexec** [comment]
Brilliant - Thank you.
